name: build sakura

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - feature/*
    paths-ignore:
      - '*.md'
      - .gitignore
      - .editorconfig
      - appveyor.yml
      - 'azure-pipelines*.yml'
      - 'ci/azure-pipelines/template*.yml'
      - '.github/*.md'
      - '.github/ISSUE_TEMPLATE/*.md'

  pull_request:
    branches:
      - master
      - feature/*
      - release/*
    paths-ignore:
      - '*.md'
      - .gitignore
      - .editorconfig
      - appveyor.yml
      - 'azure-pipelines*.yml'
      - 'ci/azure-pipelines/template*.yml'
      - '.github/*.md'
      - '.github/ISSUE_TEMPLATE/*.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: MSBuild
    runs-on: windows-latest

    strategy:
      matrix:
        config:
          #- Debug
          - Release
        platform:
          #- Win32
          - x64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    ## see https://github.com/actions/checkout
    - uses: actions/checkout@v2

    ## see https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Install Locale Emulator
      run: |
        choco install locale-emulator -y
        leproc %COMSPEC%
      shell: cmd

      #    - name: Check Locale Emulator
      #      run: |
      #        cd
      #        tools\checkcp
      #        where leproc
      #        start /wait leproc %COMSPEC% /c "d:\a\sakura\sakura\tools\checkcp.exe > d:\a\sakura\sakura\tools\cp.log"
      #        dir tools
      #        rem type tools\cp.log
      #      shell: cmd
      #
      #    # See: https://github.com/nelsonjchen/reverse-rdp-windows-github-actions
      #    - name: Download
      #      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
      #    - name: Extract
      #      run: Expand-Archive ngrok.zip
      #    - name: Auth
      #      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      #      env:
      #        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #    - name: Enable TS
      #      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
      #    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      #    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      #    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      #    - name: Create Tunnel
      #      run: .\ngrok\ngrok.exe tcp 3389

    - name: MSBuild
      run: build-sln.bat ${{ matrix.platform }} ${{ matrix.config }}
      shell: cmd

    - name: Build HTML Help
      #run: build-chm.bat
      run: start /wait leproc %COMSPEC% /c %GITHUB_WORKSPACE%\build-chm.bat
      shell: cmd

    - name: Build installer with Inno Setup
      run: build-installer.bat ${{ matrix.platform }} ${{ matrix.config }}
      shell: cmd

    - name: zipArtifacts
      run: zipArtifacts.bat ${{ matrix.platform }} ${{ matrix.config }}
      shell: cmd

    ## see https://github.com/actions/upload-artifact
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: exe ${{ matrix.platform }} ${{ matrix.config }}
        path: '*.zip'
